// Code generated by protoc-gen-go.
// source: graph/pkggraph.proto
// DO NOT EDIT!

package pkggraph

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeWaiting struct {
	Node       string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	ParentNode string `protobuf:"bytes,2,opt,name=parent_node,json=parentNode" json:"parent_node,omitempty"`
}

func (m *NodeWaiting) Reset()                    { *m = NodeWaiting{} }
func (m *NodeWaiting) String() string            { return proto.CompactTextString(m) }
func (*NodeWaiting) ProtoMessage()               {}
func (*NodeWaiting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeFinishedWaiting struct {
	Node        string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	ParentError string `protobuf:"bytes,2,opt,name=parent_error,json=parentError" json:"parent_error,omitempty"`
}

func (m *NodeFinishedWaiting) Reset()                    { *m = NodeFinishedWaiting{} }
func (m *NodeFinishedWaiting) String() string            { return proto.CompactTextString(m) }
func (*NodeFinishedWaiting) ProtoMessage()               {}
func (*NodeFinishedWaiting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeStarting struct {
	Node string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *NodeStarting) Reset()                    { *m = NodeStarting{} }
func (m *NodeStarting) String() string            { return proto.CompactTextString(m) }
func (*NodeStarting) ProtoMessage()               {}
func (*NodeStarting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NodeFinished struct {
	Node  string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *NodeFinished) Reset()                    { *m = NodeFinished{} }
func (m *NodeFinished) String() string            { return proto.CompactTextString(m) }
func (*NodeFinished) ProtoMessage()               {}
func (*NodeFinished) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NodeSending struct {
	Node      string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	ChildNode string `protobuf:"bytes,2,opt,name=child_node,json=childNode" json:"child_node,omitempty"`
	Error     string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *NodeSending) Reset()                    { *m = NodeSending{} }
func (m *NodeSending) String() string            { return proto.CompactTextString(m) }
func (*NodeSending) ProtoMessage()               {}
func (*NodeSending) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*NodeWaiting)(nil), "pkggraph.NodeWaiting")
	proto.RegisterType((*NodeFinishedWaiting)(nil), "pkggraph.NodeFinishedWaiting")
	proto.RegisterType((*NodeStarting)(nil), "pkggraph.NodeStarting")
	proto.RegisterType((*NodeFinished)(nil), "pkggraph.NodeFinished")
	proto.RegisterType((*NodeSending)(nil), "pkggraph.NodeSending")
}

func init() { proto.RegisterFile("graph/pkggraph.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2f, 0x4a, 0x2c,
	0xc8, 0xd0, 0x2f, 0xc8, 0x4e, 0x07, 0x33, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x27, 0x2e, 0x6e, 0xbf, 0xfc, 0x94, 0xd4, 0xf0, 0xc4, 0xcc, 0x92, 0xcc, 0xbc, 0x74,
	0x21, 0x21, 0x2e, 0x96, 0x3c, 0x20, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16,
	0x92, 0xe7, 0xe2, 0x2e, 0x48, 0x2c, 0x4a, 0xcd, 0x2b, 0x89, 0x07, 0x4b, 0x31, 0x81, 0xa5, 0xb8,
	0x20, 0x42, 0x20, 0xbd, 0x4a, 0x3e, 0x5c, 0xc2, 0x20, 0xda, 0x2d, 0x33, 0x2f, 0xb3, 0x38, 0x23,
	0x35, 0x05, 0x9f, 0x59, 0x8a, 0x5c, 0x3c, 0x50, 0xb3, 0x52, 0x8b, 0x8a, 0xf2, 0x8b, 0xa0, 0x86,
	0x41, 0xcd, 0x77, 0x05, 0x09, 0x29, 0x29, 0x71, 0xf1, 0x80, 0x4c, 0x0b, 0x2e, 0x49, 0x2c, 0xc2,
	0x65, 0x8c, 0x92, 0x05, 0x44, 0x0d, 0xcc, 0x46, 0xac, 0x56, 0x89, 0x70, 0xb1, 0x22, 0xdb, 0x01,
	0xe1, 0x28, 0x85, 0x41, 0xfc, 0x1b, 0x9c, 0x9a, 0x97, 0x82, 0xcb, 0x8d, 0xb2, 0x5c, 0x5c, 0xc9,
	0x19, 0x99, 0x39, 0x29, 0xc8, 0xde, 0xe5, 0x04, 0x8b, 0xf8, 0xa1, 0x98, 0xcb, 0x8c, 0x64, 0x6e,
	0x12, 0x1b, 0x38, 0x60, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x6f, 0xe7, 0xdb, 0x70,
	0x01, 0x00, 0x00,
}
