// Code generated by protoc-gen-protolog
// source: graph/pkggraph.proto
// DO NOT EDIT!

package pkggraph

import "go.pedge.io/protolog"

func init() {
	protolog.Register("pkggraph.NodeWaiting", protolog.MessageType_MESSAGE_TYPE_EVENT, func() protolog.Message { return &NodeWaiting{} })
	protolog.Register("pkggraph.NodeFinishedWaiting", protolog.MessageType_MESSAGE_TYPE_EVENT, func() protolog.Message { return &NodeFinishedWaiting{} })
	protolog.Register("pkggraph.NodeStarting", protolog.MessageType_MESSAGE_TYPE_EVENT, func() protolog.Message { return &NodeStarting{} })
	protolog.Register("pkggraph.NodeFinished", protolog.MessageType_MESSAGE_TYPE_EVENT, func() protolog.Message { return &NodeFinished{} })
	protolog.Register("pkggraph.NodeSending", protolog.MessageType_MESSAGE_TYPE_EVENT, func() protolog.Message { return &NodeSending{} })
}

func (m *NodeWaiting) ProtologName() string {
	return "pkggraph.NodeWaiting"
}
func (m *NodeFinishedWaiting) ProtologName() string {
	return "pkggraph.NodeFinishedWaiting"
}
func (m *NodeStarting) ProtologName() string {
	return "pkggraph.NodeStarting"
}
func (m *NodeFinished) ProtologName() string {
	return "pkggraph.NodeFinished"
}
func (m *NodeSending) ProtologName() string {
	return "pkggraph.NodeSending"
}
