// Code generated by protoc-gen-go.
// source: http/protolog.proto
// DO NOT EDIT!

package pkghttp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/google-protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Call struct {
	Path       string                    `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	StatusCode uint32                    `protobuf:"varint,2,opt,name=status_code" json:"status_code,omitempty"`
	Duration   *google_protobuf.Duration `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}

func (m *Call) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type ServerCouldNotStart struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ServerCouldNotStart) Reset()         { *m = ServerCouldNotStart{} }
func (m *ServerCouldNotStart) String() string { return proto.CompactTextString(m) }
func (*ServerCouldNotStart) ProtoMessage()    {}

type ServerStarting struct {
}

func (m *ServerStarting) Reset()         { *m = ServerStarting{} }
func (m *ServerStarting) String() string { return proto.CompactTextString(m) }
func (*ServerStarting) ProtoMessage()    {}

type ServerFinished struct {
	Error    string                    `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Duration *google_protobuf.Duration `protobuf:"bytes,2,opt,name=duration" json:"duration,omitempty"`
}

func (m *ServerFinished) Reset()         { *m = ServerFinished{} }
func (m *ServerFinished) String() string { return proto.CompactTextString(m) }
func (*ServerFinished) ProtoMessage()    {}

func (m *ServerFinished) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}
