// Code generated by protoc-gen-protolog
// source: http/protolog.proto
// DO NOT EDIT!

package pkghttp

import "go.pedge.io/protolog"

func init() {
	protolog.Register("pkghttp.Call", func() protolog.Message { return &Call{} })
	protolog.Register("pkghttp.ServerCouldNotStart", func() protolog.Message { return &ServerCouldNotStart{} })
	protolog.Register("pkghttp.ServerStarting", func() protolog.Message { return &ServerStarting{} })
	protolog.Register("pkghttp.ServerFinished", func() protolog.Message { return &ServerFinished{} })
}

func (m *Call) ProtologName() string {
	return "pkghttp.Call"
}
func (m *ServerCouldNotStart) ProtologName() string {
	return "pkghttp.ServerCouldNotStart"
}
func (m *ServerStarting) ProtologName() string {
	return "pkghttp.ServerStarting"
}
func (m *ServerFinished) ProtologName() string {
	return "pkghttp.ServerFinished"
}
